/**
 * @description Add your message codes here
 */
export type ICodeDTO =
  | 'FAILED_TO_CREATE_NOTIFICATION'
  | 'CAN_NOT_RESOLVE_RELATION'
  | 'FAILED_TO_CREATE_LEAD'
  | 'FAILED_TO_GET_SESSION'
  | 'EMAIL_ALREADY_EXISTS'
  | 'INVALID_DELAY_FORMAT'
  | 'INVALID_LOGIN_DATA'
  | 'TOO_MANY_REQUESTS'
  | 'FAILED_TO_CREATE'
  | 'CAN_NOT_SLUGIFY'
  | 'FAILED_TO_LIST'
  | 'INVALID_CLAUSE'
  | 'FILE_NOT_FOUND'
  | 'INVALID_TOKEN'
  | 'AUTHENTICATED'
  | 'GENERATED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CREATED'
  | 'UPDATED'
  | 'DELETED'
  | 'PATCHED'
  | 'LISTED'
  | 'FOUND'
  | 'SENT';
